// Copyright Consensys Software Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
package util

import (
	"bytes"
	"fmt"
	"os/exec"
	"testing"

	"github.com/LFDT-Lineth/zkc/pkg/zkc/gogen"
	"github.com/LFDT-Lineth/zkc/pkg/zkc/vm"
)

// runGogenExecutionTest cross-checks the generated-Go ("native") executor against
// a test case: it generates Go from the word machine (over Uint — the same
// machine the reference executor interprets), compiles it once (cached), runs it
// on the test inputs as a subprocess, and verifies the outputs and accept/reject
// verdict match — exactly as runExecutionTest does for a Core.
//
// Programs the generator cannot yet handle (wide registers/constants/moduli, …)
// are skipped rather than failed: gogen coverage grows over time.
// Note: runGogenExecutionTest shares its *testing.T with the whole CheckValid run
// (there is no enclosing t.Run), so it must never call t.Skip / t.Fatal — doing so
// would abort the surrounding bytecode and constraint checks.  Unsupported programs
// are logged and skipped; only genuine mismatches use t.Errorf.
func runGogenExecutionTest(t *testing.T, wm *vm.WordMachine[vm.Uint], test TestCase, cfg vm.WordConfig) {
	if _, err := exec.LookPath("go"); err != nil {
		// No Go toolchain: silently skip this optional cross-check.
		return
	}
	// Generate native Go for this machine.
	src, err := vm.GenerateGo(wm, vm.GoGenConfig{})
	if err != nil {
		t.Logf("[gogen %s]%s:%d unsupported, skipping: %v", cfg.Name, test.filename, test.line, err)
		return
	}
	// Compile once (binaries are cached by source across test cases / vectors).
	prog, err := gogen.Build(src)
	if err != nil {
		t.Errorf("[gogen %s]%s:%d build: %v", cfg.Name, test.filename, test.line, err)
		return
	}
	// The generated harness shares the byte encoding the reference executor
	// uses, so the test's raw JSON data feeds it unchanged.
	_, outputs := decodeInputsOutputs(t, wm, test.data)

	got, errored, runErr := gogen.Run(prog, test.data)
	if runErr != nil {
		t.Errorf("[gogen %s]%s:%d run: %v", cfg.Name, test.filename, test.line, runErr)
		return
	}

	var errs []error
	// Mirror runExecutionTest's accept/reject logic.
	switch {
	case errored && test.expected:
		errs = append(errs, fmt.Errorf("rejected accepted trace"))
	case !errored && !test.expected:
		errs = append(errs, fmt.Errorf("accepted rejected trace"))
	case !errored && test.expected:
		errs = append(errs, compareGogenOutputs(wm, outputs, got)...)
	}

	for _, err := range errs {
		t.Errorf("[gogen %s]%s:%d %v", cfg.Name, test.filename, test.line, err)
	}
}

// compareGogenOutputs checks each output memory's generated bytes against the
// reference encoding of the expected words.  Comparing in the byte domain (via
// the reference vm.EncodeBytes) cross-checks the harness's own packing too.
func compareGogenOutputs(wm *vm.WordMachine[vm.Uint], expected map[string][]vm.Uint, got map[string][]byte) []error {
	var errs []error
	//
	for it := wm.Outputs(); it.HasNext(); {
		o := it.Next()
		name := o.Name()
		want := vm.EncodeBytes(expected[name], o.Geometry())
		//
		if have := got[name]; !bytes.Equal(have, want) {
			errs = append(errs, fmt.Errorf("output %q: expected 0x%x, got 0x%x", name, want, have))
		}
	}
	//
	return errs
}
