// Copyright Consensys Software Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
package util

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	"github.com/LFDT-Lineth/zkc/pkg/cmd/zkc/gogen"
	"github.com/LFDT-Lineth/zkc/pkg/zkc/vm"
)

// errGoGenUnsupported marks a program the generated-Go backend cannot represent
// (e.g. a wide multi-limb division hint, which needs full-value division beyond
// gogen's 64/128-bit operand model).  Such programs are logged and skipped by
// the harness rather than failed — gogen coverage grows over time.  It is
// distinct from a genuine build failure (gogen emitted invalid Go), which
// remains a hard error.
var errGoGenUnsupported = errors.New("gogen cannot represent program")

// runGogenExecutionTest cross-checks the generated-Go ("native") executor against
// a test case: it generates Go from the word machine (over Uint — the same
// machine the reference executor interprets), compiles it once (cached), runs it
// on the test inputs as a subprocess, and verifies the outputs and accept/reject
// verdict match — exactly as runExecutionTest does for a Core.
//
// Programs the generator cannot yet handle (wide registers/constants/moduli, …)
// are skipped rather than failed: gogen coverage grows over time.
// Note: runGogenExecutionTest shares its *testing.T with the whole CheckValid run
// (there is no enclosing t.Run), so it must never call t.Skip / t.Fatal — doing so
// would abort the surrounding bytecode and constraint checks.  Unsupported programs
// are logged and skipped; only genuine mismatches use t.Errorf.
func runGogenExecutionTest(t *testing.T, program vm.Program[vm.Uint], prog string, test TestCase) {
	var (
		_, outputs = decodeInputsOutputs(t, program, test.data)
	)

	// Discard the program's debug/fail output: this cross-check compares the
	// output memories and accept/reject verdict, not the printed messages.
	got, errored, runErr := gogen.Run(prog, gogenInputs(program, test.data), io.Discard)
	if runErr != nil {
		t.Errorf("[gogen]%s:%d run: %v", test.filename, test.line, runErr)
		return
	}

	var errs []error
	// Mirror runExecutionTest's accept/reject logic.
	switch {
	case errored && test.expected:
		errs = append(errs, fmt.Errorf("rejected accepted trace"))
	case !errored && !test.expected:
		errs = append(errs, fmt.Errorf("accepted rejected trace"))
	case !errored && test.expected:
		errs = append(errs, compareGogenOutputs(program, outputs, got)...)
	}

	for _, err := range errs {
		t.Errorf("[gogen]%s:%d %v", test.filename, test.line, err)
	}
}

// Build a go binary representing the given word machine.
func buildGogenProgram(t *testing.T, program vm.Program[vm.Uint]) (string, error) {
	//
	t.Helper()
	//
	if _, err := exec.LookPath("go"); err != nil {
		// No Go toolchain: silently skip this optional cross-check.
		return "", err
	}
	// Generate native Go for this machine.  A generation failure means gogen
	// cannot yet represent this program (an unsupported feature), which is a skip
	// rather than a failure — hence the errGoGenUnsupported marker.
	src, err := vm.GenerateGo(program, vm.GoGenConfig{})
	if err != nil {
		return "", fmt.Errorf("%w: %v", errGoGenUnsupported, err)
	}
	// Compile the generated main package for this test case.
	dir := t.TempDir()
	prog := filepath.Join(dir, "prog")

	if err := os.WriteFile(filepath.Join(dir, "main.go"), []byte(src), 0o644); err != nil {
		return "", err
	}

	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module zkcgen\n\ngo 1.24\n"), 0o644); err != nil {
		return "", err
	}

	cmd := exec.Command("go", "build", "-o", prog, ".")
	cmd.Dir = dir

	if out, err := cmd.CombinedOutput(); err != nil {
		return "", fmt.Errorf("build error: %v\n%s\n--- source ---\n%s", err, out, src)
	}

	return prog, nil
}

func gogenInputs(program vm.Program[vm.Uint], data map[string][]byte) map[string][]byte {
	inputs := make(map[string][]byte)

	for it := program.Inputs(); it.HasNext(); {
		input := it.Next()
		if bytes, ok := data[input.Name()]; ok {
			inputs[input.Name()] = bytes
		}
	}

	return inputs
}

// compareGogenOutputs checks each output memory's generated bytes against the
// reference encoding of the expected words.  Comparing in the byte domain (via
// the reference vm.EncodeBytes) cross-checks the harness's own packing too.
func compareGogenOutputs(program vm.Program[vm.Uint], expected map[string][]vm.Uint, got map[string][]byte) []error {
	var errs []error
	//
	for it := program.Outputs(); it.HasNext(); {
		o := it.Next()
		name := o.Name()
		want := vm.EncodeBytes(expected[name], o)
		//
		if have := got[name]; !bytes.Equal(have, want) {
			errs = append(errs, fmt.Errorf("output %q: expected 0x%x, got 0x%x", name, want, have))
		}
	}
	//
	return errs
}
